version: '2'
services:
  iam-app:
    image: iam
    environment:
      # - _JAVA_OPTIONS=-Xmx512m -Xms256m

      - SPRING_DATASOURCE_URL=jdbc:mysql://iam-mysql:3306/iam?useUnicode=true&characterEncoding=utf8&useSSL=false
      - SECURITY_OAUTH2_CLIENT_CLIENT_ID=internal
      - SECURITY_OAUTH2_CLIENT_CLIENT_SECRET=internal
      - SECURITY_OAUTH2_RESOURCE_USER_INFO_URI=http://keycloak:9080/auth/realms/ecommerce-realm/protocol/openid-connect/userinfo
    ports:
      - 8080:8080

  iam-mysql:
    extends:
      file: mysql.yml
      service: iam-mysql

  keycloak:
    extends:
      file: keycloak.yml
      service: keycloak
