server:
  port: 8081

keycloak:
  realm: ecommerce-realm
  auth-server-url: http://localhost:8080/auth/
  ssl-required: external
  use-resource-role-mappings: false
  resource: ecommerce-app
  bearer-only: true
  principal-attribute: preferred_username
  confidential-port: 0
  enabled: true


spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/ecommerce?autoReconnect=true&useSSL=false
    username: root
    password: root
    hikari:
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        allowPublicKeyRetrieval: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    properties:

      hibernate.hbm2ddl.auto: update
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false